// Phase 5 presentation constants. Visual sizes, anchors and animation timings live
// here, separate from gameplay collision (gameplay.ts HITBOX) and B-01 (tuning.ts).
// Art is generated by tools/art/build-art.mjs into public/assets/.

export const ASSET_PATH = 'assets/';
export const ATLAS = 'jungle';

export const IMAGES = ['ground-top', 'ground-fill', 'ground-side-l', 'ground-side-r', 'ground-cap-l', 'ground-cap-r', 'bg-far', 'bg-near', 'canopy-night',
  'cave-top', 'cave-fill', 'cave-side-l', 'cave-side-r', 'cave-cap-l', 'cave-cap-r', 'cave-far', 'cave-near'] as const;

/** Font sheets (RetroFont): 8x10 cells, 16 per row. */
export const FONT_CHARS = " !'-./0123456789:?ABCDEFGHIJKLMNOPQRSTUVWXYZ+>";
export const FONTS = { plain: 'font', gold: 'font-gold', ink: 'font-ink' } as const;

export const DK = {
  /** Drawing anchor: feet centre, aligned with the bottom centre of the 12x16 body. */
  cell: 32,
  idleMsPerFrame: 520,
  /** Walk/run frames advance with distance travelled, so feet do not slide. */
  walkPxPerFrame: 4.7,
  runPxPerFrame: 6,
  gaitFrames: 6,
  runThreshold: 75,
  rollMsPerFrame: 37.5,
  rollFrames: 8,
  throwPoseMs: 200,
  cheerMsPerFrame: 300,
  /** Carried barrel centre relative to the feet: above the raised hands (visual only). */
  carryOffset: { x: 0, y: -35 },
  hurtGhostMs: 320,
} as const;

export const TIMING = {
  gnawtyMsPerFrame: 170,
  snakeMsPerFrame: 200,
  tireSquashMs: 160,
  gnawtyDefeatMs: 520,
  bananaMsPerFrame: 140,
  bananaIdleMs: 700,
  starBarrelMsPerFrame: 260,
  sparkleMs: 180,
  hitMs: 180,
  debrisMs: 260,
  checkpointBurstMs: 420,
  barrelRollPxPerFrame: 5,
} as const;

/** Parallax factors for the two backdrop layers (screen-anchored TileSprites). */
export const PARALLAX = { far: 0.25, near: 0.55, nearY: 36, nearHeight: 108 } as const;

export const DEPTH = { far: -30, near: -20, decor: -10, ground: 0, canopy: 3.5, items: 4, enemies: 5, player: 6, carried: 7, fx: 8, debug: 9, hud: 20, overlay: 30 } as const;
