import Phaser from 'phaser';
import { type Action, type InputSnapshot, InputController } from './input';
import { pixelText } from './pixels';
import { ASSET_PATH, ATLAS, FONTS, IMAGES } from './art-spec';

export const SCENE_CHANGED = 'berto:scene-changed';

export class BootScene extends Phaser.Scene {
  constructor() { super('BootScene'); }
  preload() {
    // Phase 5 art, generated by tools/art/build-art.mjs (npm run art).
    this.load.setPath(ASSET_PATH);
    this.load.atlas(ATLAS, 'jungle-atlas.png', 'jungle-atlas.json');
    for (const name of IMAGES) this.load.image(name, `${name}.png`);
    for (const font of Object.values(FONTS)) this.load.image(font, `${font}.png`);
  }
  create() {
    this.game.events.emit(SCENE_CHANGED, 'BootScene');
    this.cameras.main.setBackgroundColor('#182d2b');
    const g = this.add.graphics();
    pixelText(g, 'BOOT', 72, 70, 0xc8dbac);
    this.time.delayedCall(150, () => this.scene.start(this.registry.get('diagnostic') ? 'DiagnosticScene' : this.registry.get('lab') ? 'MovementLabScene' : this.registry.get('campaign') ? this.registry.get('cinematic')?'TitleScene':'WorldMapScene' : 'JungleGreyboxScene'));
  }
}

export class DiagnosticScene extends Phaser.Scene {
  constructor() { super('DiagnosticScene'); }
  create() {
    this.game.events.emit(SCENE_CHANGED, 'DiagnosticScene');
    const input = this.registry.get('controls') as InputController;
    const g = this.add.graphics();
    const redraw = (state: InputSnapshot) => {
      g.clear();
      g.fillStyle(0xc8dbac).fillRect(0, 0, 160, 144);
      g.fillStyle(0x1d3931).fillRect(4, 4, 152, 136);
      g.fillStyle(0xc8dbac).fillRect(5, 5, 150, 134);
      pixelText(g, 'PHASE A / INPUT LAB', 12, 12, 0x1d3931);
      pixelText(g, '160 X 144', 12, 23, 0x526f46);
      const colors = [0x1d3931, 0x526f46, 0x94b579, 0xe3edbc];
      colors.forEach((color, i) => g.fillStyle(color).fillRect(12 + i*34, 35, 34, 10));
      // Adjacent 1px lines and checkerboard expose unwanted smoothing.
      for (let x = 12; x < 148; x++) {
        for (let y = 49; y < 59; y++) {
          g.fillStyle((x + y) % 2 ? 0xc8dbac : 0x1d3931).fillRect(x, y, 1, 1);
        }
      }
      const button = (action: Action, x: number, y: number, w: number, h: number, label: string) => {
        g.fillStyle(state[action] ? 0x1d3931 : 0x94b579).fillRect(x, y, w, h);
        pixelText(g, label, x + Math.floor((w - (label.length*4-1))/2), y + Math.floor((h-5)/2), state[action] ? 0xe3edbc : 0x1d3931);
      };
      button('up', 33, 68, 17, 15, 'W');
      button('left', 15, 84, 17, 15, 'A');
      button('right', 51, 84, 17, 15, 'D');
      button('down', 33, 100, 17, 15, 'S');
      g.fillStyle(0x526f46).fillRect(33, 84, 17, 15);
      button('b', 94, 94, 19, 19, 'B');
      button('a', 121, 80, 19, 19, 'A');
      pixelText(g, 'J', 102, 116, 0x526f46);
      pixelText(g, 'K', 129, 102, 0x526f46);
      button('start', 20, 123, 37, 10, 'START');
      pixelText(g, 'KEYS ' + Object.values(state).filter(Boolean).length, 111, 129, 0x1d3931);
    };
    const unsubscribe = input.subscribe(redraw);
    this.events.once(Phaser.Scenes.Events.SHUTDOWN, unsubscribe);
  }
}
